Webapp/Models/Payment.cs
using System;
using System.Collections.Generic;

namespace Webapp.Models
{
    public class Payment
    {
        public int Id { get; set; }
        public Customer Customer { get; set; }
        public int CustomerId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }
        public decimal TotalAmount  { get; set; }
        public DateTime PaymentDate { get; set; }

        public List<Rental> Rentals { get; set; }

    }
}

Webapp/Controllers/PaymentsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Webapp.Models;

namespace Webapp.Controllers
{
    public class PaymentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Payments
        public ActionResult Index()
        {
            var payments = db.Payments.Include(p => p.ApplicationUser).Include(p => p.Customer);
            return View(payments.ToList());
        }

        // GET: Payments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email");
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "FirstName");
            ViewBag.RentMovieId = new SelectList(db.Movies, "Id", "Title");

            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Payment payment)
        {
            payment.PaymentDate = DateTime.Now;
            
            payment.Rentals.ForEach(item =>
            {
                item.CustomerId = payment.CustomerId;
                item.ApplicationUserId = payment.ApplicationUserId;
            });

            if (ModelState.IsValid)
            {
                db.Payments.Add(payment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", payment.ApplicationUserId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "FirstName", payment.CustomerId);
            ViewBag.RentMovieId = new SelectList(db.Movies, "Id", "Title");

            return View(payment);
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", payment.ApplicationUserId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "FirstName", payment.CustomerId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,ApplicationUserId,TotalAmount,PaymentDate")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", payment.ApplicationUserId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "FirstName", payment.CustomerId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payment payment = db.Payments.Find(id);
            db.Payments.Remove(payment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public PartialViewResult createRent(Rental rent)
        {
           ViewBag.Movie =  db.Movies.Find(rent.RentMovieId);
            return PartialView(rent);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Webapp/Views/Payments/Create.cshtml
@model Webapp.Models.Payment

@{
    ViewBag.Title = "Create";
    AjaxOptions ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "tbody",
        InsertionMode = InsertionMode.InsertAfter,
        OnComplete = "onComplete"
    };
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Rentar <a href="@Url.Action("Index")" class="btn btn-primary pull-right"><i class="fa fa-arrow-circle-left"></i> volver a la lista</a></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="col-md-6">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Socio</label>
                <div class="col-md-10">
                    @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Usuario creador</label>
                <div class="col-md-10">
                    @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Monto total
                <div class="col-md-10">
                    <input type="text" readonly="" id="amount" class="form-control"/>
                    <input type="hidden" readonly="" name ="TotalAmount" id="totalAmount" class="form-control"/>
                </div>
            </div>
            <table id="dataTables-example" class="table table-striped table-bordered table-hover">

                <thead>
                    <tr>
                        <th>
                            Pelicula
                        </th>
                        <th>
                            Precio
                        </th>
                        <th>
                            Fecha de devolucion
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody id="tbody"></tbody>
            </table>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
<div class="col-md-6">
    @using (Ajax.BeginForm("createRent", "Payments", ajaxOptions))
    {


        <div class="form-horizontal">
            @Html.AntiForgeryToken()
            

            <div class="form-group">
                <label class="control-label col-md-2">Socio</label>
                <div class="col-md-10">
                    @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Pelicula</label>
                <div class="col-md-10">
                    @Html.DropDownList("RentMovieId", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Fecha de retorno</label>
                <div class="col-md-10">
                    <input type="date" name="ReturnDate" class = "form-control" />
                   
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Rentar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunob")

    <script>
        function deleteRow(parameters) {
            $('#' + parameters).remove();
            sumRows();
        }

        function onComplete() {
            sumRows();
        }

        function sumRows() {
            var totals = 0;
           var $dataRows = $("#tbody tr");
            $dataRows.each(function () {
                $(this).find('.rowDataSd').each(function (i) {
                    totals+= parseInt($(this).html());
                });
            });
            $('#totalAmount').val(totals);
            $('#amount').val(totals);
            
        }
    </script>
}

Webapp/Views/Payments/Delete.cshtml
@model Webapp.Models.Payment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Webapp/Views/Payments/Details.cshtml
@model Webapp.Models.Payment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Webapp/Views/Payments/Edit.cshtml
@model Webapp.Models.Payment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webapp/Views/Payments/Index.cshtml
@model IEnumerable<Webapp.Models.Payment>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Listado de pagos
            <a href="@Url.Action("Create","Payments")" class="btn btn-primary pull-right"><i class="fa fa-file-code-o"></i> Nueva pago</a>
        </h1>

    </div>
    <!-- /.col-lg-12 -->
</div>
<table id="dataTables-example" class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>
            Usuario
        </th>
        <th>
            Socio
        </th>
        <th>
           Monto total
        </th>
        <th>
            Fecha de pago
        </th>
        <th></th>
    </tr>
        </thead>
    
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FirstName)   @Html.DisplayFor(modelItem => item.Customer.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentDate)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.Id})
            </td>
        </tr>
    }
</tbody>
</table>

Webapp/Views/Payments/createRent.cshtml
@model Webapp.Models.Rental
@{
    var guid = Guid.NewGuid().ToString();
    var movie = ViewBag.Movie;
    }

<tr id="@guid">
    <input type="hidden" name="Rentals.index" value="@guid"/>
    <input type="hidden" name="Rentals[@guid].RentMovieId" value="@movie.Id"/>
    <input type="hidden" name="Rentals[@guid].ReturnDate" value="@Model.ReturnDate"/>
    <td>@movie.Title</td>
    <td class="rowDataSd">@movie.Price</td>
    <td>@Model.ReturnDate</td>
    <td>
        <a href="#" onclick="deleteRow('@guid')" class="btn btn-danger"><i class="fa fa-times-circle"></i></a>
    </td>
</tr>